---
- name: Prepare Converge
  hosts: all
  tasks:
    - name: "Install python3"
      package:
        name: "python3"
        state: present
- name: Converge
  hosts: all
  roles:
    - role: firewalld
